# Generated by Django 4.1.3 on 2022-12-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_id', models.CharField(max_length=10, verbose_name='self_id')),
                ('is_ended', models.BooleanField(verbose_name='is_ended')),
                ('participant_1', models.CharField(max_length=30, verbose_name='participant_1')),
                ('participant_2', models.CharField(max_length=30, verbose_name='participant_2')),
                ('score', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='key')),
                ('user_login', models.CharField(max_length=50, verbose_name='user_login')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('psw', models.CharField(max_length=50, verbose_name='psw')),
            ],
        ),
    ]
