# Generated by Django 4.1.3 on 2022-12-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='is_ended',
            field=models.IntegerField(verbose_name='is_ended'),
        ),
    ]
